# Generated by Django 4.1.2 on 2022-10-31 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Last_Name.', max_length=50)),
                ('first_name', models.CharField(help_text='First_Name.', max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Last_Name.', max_length=50)),
                ('first_name', models.CharField(help_text='First_Name.', max_length=50)),
                ('email_address', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=70)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('cargo_tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address_type', models.CharField(choices=[('pickup_point', 'Pickup Point'), ('drop_off_point', 'Drop Off Point')], default='pickup_point', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.customer')),
                ('done_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to=settings.AUTH_USER_MODEL)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.vehicle')),
            ],
        ),
    ]
